CREATE TABLE STUDENTS (
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    USERNAME VARCHAR(255),
    EMAIL VARCHAR(255),
    STUDENTID INT,
    PRIMARY KEY(STUDENTID)
);

CREATE TABLE TEACHERS (
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    USERNAME VARCHAR(255),
    EMAIL VARCHAR(255),
    TEACHERID INT,
    PRIMARY KEY(TEACHERID)
);

CREATE TABLE QUIZZES (
    QUIZID INT,
    QUIZNAME VARCHAR(255),
    QUIZSIZE INT,
    PRIMARY KEY(QUIZID)
);

CREATE TABLE QUIZQUESTIONS (
    QUIZID INT,
    QUIZQUESTIONSID INT,
    QUESTION VARCHAR(255),
    CORRECTANSWER VARCHAR(255),
    INCORRECTANSWER VARCHAR(255),
    PRIMARY KEY(QUIZQUESTIONSID),
    FOREIGN KEY(QUIZID) REFERENCES QUIZZES(QUIZID)
);